apiVersion: v1
kind: Pod
metadata:
  name: pod-thin
  labels:
    name: busybox-test
spec:
  restartPolicy: Always
  containers:
    - image: busybox:1.36
      command: ["/bin/sh", "-c"]
      args: [ "tail -f /dev/null" ]
      name: busybox
      volumeMounts:
        - name: vol
          mountPath: /mnt/vol
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: pvc-thin
